export default {
  login: 'api/user/login',
  signout: 'api/user/signout',
  queryPlan: 'api/plan',
  addPlan: 'api/plan',
  updatePlan: 'api/plan',
  delPlan: 'api/plan',
  queryRibbonType: 'api/ribbonType',
  addRibbonType: 'api/ribbonType',
  updateRibbonType: 'api/ribbonType',
  delRibbonType: 'api/ribbonType',
  queryUser: 'api/user',
  addUser: 'api/user',
  updatePassword: 'api/user',
  delUser: 'api/user',
  queryMelt: 'api/melt',
  addMelt: 'api/melt',
  updateMelt: 'api/melt',
  delMelt: 'api/melt',
};